[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.pip-cache        # exclude a few common directories in the
    | \.git          # root of the project
    | \.venv-cache
    | \.venv
    | \.idea
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''